name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]  # Ã½a-da master â€” proÃ½ektiÅˆe gÃ¶rÃ¤ Ã¼Ã½tgedip bilersiÅˆ

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Repositorini clone et
        uses: actions/checkout@v3

      - name: ğŸ Python gurmak
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Kitaplary gurmak
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸš€ Boty baÅŸlatmak
        run: |
          python main.py
